name: Push Pipeline
on:
  workflow_dispatch:

jobs:
  runner:
    runs-on: [self-hosted, linux, x64, ubuntu-2204]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Time
        run: echo "The time is $(date)."